### ISSUE TITLE
Do you still use your alarmPi? 

### ISSUE THREAD

**Issue by deltamelter** [mattdy/alarmpi#6]
@mattdy I made a version of this project out of an old internet radio which closed it's streaming services about 10 year ago.
I re-used the built in LCD, rotary encoder and built in buttons and speaker, added an i2c stereo amp and hooked it all up to a raspi A+

For 8 or so of the last 10 years my wife was happily being awoken by the random choice of alarm sound (mostly recorded by the kids when they sounded funny and adorable (now just embarrasing for them to hear their younger selves and the most annoying alarm))  That bit still works but the googletts stopped working long ago as did the BBC streams that have moved to proprietary DRM system.

Anyway I was just looking to add a large illuminated dome (arcade style) button and maybe some Home Assistant integration when I looked up the original project here.

I was wondering if you made any advancements to this project over the last 10 years or if you even still use it 😀

**Comment by mattdy** [comment]
Hi!

I'm afraid I don't use my AlarmPi any more, I moved to using a [Lenovo Smart Clock](https://www.lenovo.com/in/en/smart-clock/) for the integration with Google Home.

Very happy to hear that this project is still finding use today!

**Comment by deltamelter** [comment]
> Hi!
> 
> I'm afraid I don't use my AlarmPi any more, I moved to using a [Lenovo Smart Clock](https://www.lenovo.com/in/en/smart-clock/) for the integration with Google Home.
> 
> Very happy to hear that this project is still finding use today!

Funny, I was looking at those lenovo smart clocks (clock only version) a few year ago, are they "mod-able"?  They were going for £19 in currys for a long time 😁 

I had to work out my 10 year old wiring and forgot about wiringpi numbering.  Eventually found 2 free GPIOs for the button and it's illumination LED, now there is a 60mm bright red blinking arcade button on the top to cancel the alarm.
still got a few more years life in it...

**Comment by mattdy** [comment]
I haven't tried to modify it, it's been working great for me so far!

Glad that you've managed to breathe some new life into your project :-)

**Comment by deltamelter** [comment]
longshot, but do you happen to recall anything about the LCDControl library you used in alarmPi.  I came to look at a modification to this, but my LCDThread.py imports a different library than you mention and I only have LCDlib.pyc
`from LCDlib import LCDlib` in LCDThread.py
It seems to have the same general function and methods as LCDControl, but I guess I might have needed to use something different for accessing the built in LCD, or did you perhaps change this?
It's all a long time ago now and I notice that your LCDConctrol project is no longer around.

**Comment by mattdy** [comment]
Sorry, it's been a long time since I wrote that! From what I remember, the library I was using was deprecated so I elected not to move that project across to GitHub when I migrated everything off my personal repository several years ago.
